export const LEGAL_CONSENT_VERSION = "v1.0-2026-03";

export type LegalTextKey = "privacy" | "terms";

/** Verbatim text of the documents Eren issued in March 2026 (docx → paragraphs). */
export const LEGAL_TEXTS: Record<LegalTextKey, { title: string; paragraphs: string[] }> = {
  privacy: { title: "Aydınlatma Metni", paragraphs: [
  "KİŞİSEL VERİLERİN İŞLENMESİNE İLİŞKİN",
  "AYDINLATMA METNİ",
  "Route Assistant Uygulaması",
  "1. Amaç",
  "Bu Aydınlatma Metni, 6698 sayılı Kişisel Verilerin Korunması Kanunu (\"KVKK\") Madde 10 ve AB Genel Veri Koruma Tüzüğü (\"GDPR\") Madde 13 kapsamında, Uptecra Teknoloji A.Ş. (\"Şirket\") tarafından Route Assistant uygulaması (\"Uygulama\") aracılığıyla toplanan kişisel verileriniz hakkında sizi bilgilendirmek amacıyla hazırlanmıştır.",
  "2. İşlenen Kişisel Veriler ve İşleme Amaçları",
  "Konum verisi yaklaşık 1 km² hassasiyetinde (koordinat yuvarlama) saklanmakta olup kesin adres bilgisi hiçbir zaman kaydedilmemektedir. Hız ve ivme verileri yalnızca cihazınızda işlenmekte, sunucularımıza aktarılmamaktadır.",
  "3. Kişisel Verilerin Aktarıldığı Üçüncü Taraflar",
  "Yurt dışına aktarım, KVKK Madde 9 ve GDPR Madde 46 kapsamında uygun güvenceler (Standart Sözleşme Maddeleri) ile gerçekleştirilmektedir.",
  "4. Kişisel Verilerin Saklanma Süreleri",
  "Hesap verileri (ad, soyad, telefon): Hesabınız aktif olduğu sürece saklanır. Hesap silme talebinden 30 gün sonra kalıcı olarak silinir.",
  "Rota ve konum geçmişi: Oluşturma tarihinden itibaren 12 ay saklanır, ardından otomatik olarak silinir.",
  "Ses kaydı ve transkript: Sesli asistan oturumu tamamlandığında anında silinir, kalıcı olarak depolanmaz.",
  "OTP kodu: Kullanım veya 5 dakikalık süre sonu ile anında silinir.",
  "Hız / ivme verisi: Yalnızca cihazınızda, oturum süresince tutulur. Sunucuya gönderilmez.",
  "5. İlgili Kişi Hakları",
  "KVKK Madde 11 ve GDPR Madde 15-22 kapsamında aşağıdaki haklara sahipsiniz:",
  "Bu haklarınızı kullanmak için Uygulama içindeki Hesabım ekranını kullanabilir ya da info@uptecra.com adresine e-posta gönderebilirsiniz. Talepleriniz en geç 30 gün içinde yanıtlanacaktır.",
  "GDPR kapsamındaki kullanıcılar, şikayetlerini yetkili veri koruma otoritesine (ilgili AB üyesi ülkedeki DPA) iletme hakkına sahiptir. Türkiye'deki kullanıcılar için başvuru mercii Kişisel Verileri Koruma Kurumu'dur (kvkk.gov.tr).",
  "6. Güvenlik Önlemleri",
  "Kişisel verileriniz aşağıdaki teknik ve idari önlemlerle korunmaktadır:",
  "Tüm veri iletişimi TLS 1.2 veya üzeri şifreleme ile gerçekleştirilmektedir.",
  "Telefon numaranız AES-256-GCM algoritması ile şifrelenerek saklanmaktadır.",
  "Konum verisi koordinat yuvarlama yöntemi ile anonimleştirilmektedir (~1 km² hassasiyet).",
  "Ses kayıtları hiçbir zaman kalıcı depolanmamakta; oturum bitişinde otomatik olarak silinmektedir.",
  "Veritabanı erişimi rol tabanlı yetkilendirme (RBAC) ile kısıtlanmaktadır.",
  "7. Çerez ve Benzeri Teknolojiler",
  "Uygulama, oturum yönetimi için JWT tabanlı kimlik doğrulama kullanmaktadır. Üçüncü taraf izleme çerezleri kullanılmamaktadır.",
  "8. Değişiklikler",
  "Bu Aydınlatma Metni güncellendiğinde yeni versiyon Uygulama içinde ve web sitemizde yayımlanacaktır. Önemli değişiklikler için kullanıcılar bilgilendirilecektir.",
  "9. İletişim",
  "PRIVACY NOTICE",
  "PROCESSING OF PERSONAL DATA",
  "Route Assistant Application",
  "1. Purpose",
  "This Privacy Notice is prepared pursuant to Article 10 of the Turkish Personal Data Protection Law No. 6698 (\"KVKK\") and Article 13 of the EU General Data Protection Regulation (\"GDPR\") to inform you about the personal data collected by Uptecra Teknoloji A.S. (\"Company\") through the Route Assistant application (\"App\").",
  "2. Personal Data Processed and Purposes",
  "Location data is stored at approximately 1 km² precision (coordinate rounding); exact addresses are never recorded. Speed and acceleration data is processed solely on your device and never transmitted to our servers.",
  "3. Third-Party Recipients",
  "International transfers are carried out with appropriate safeguards under KVKK Article 9 and GDPR Article 46 (Standard Contractual Clauses).",
  "4. Retention Periods",
  "Account data (name, surname, phone): retained while your account is active; permanently deleted 30 days after a deletion request.",
  "Route and location history: retained for 12 months from creation date, then automatically deleted.",
  "Voice recordings and transcripts: deleted immediately when the voice assistant session ends; never stored permanently.",
  "OTP codes: deleted immediately upon use or after a 5-minute expiry.",
  "Speed / acceleration data: held on your device for the session duration only; never sent to servers.",
  "5. Your Rights",
  "Under KVKK Article 11 and GDPR Articles 15-22, you have the following rights:",
  "To exercise your rights, use the Account section in the App or email info@uptecra.com. Requests will be responded to within 30 days.",
  "EU/EEA users have the right to lodge a complaint with their local data protection authority. Users in Turkey may contact the Personal Data Protection Authority (kvkk.gov.tr).",
  "6. Security Measures",
  "All data transmission is encrypted using TLS 1.2 or higher.",
  "Phone numbers are stored encrypted using AES-256-GCM.",
  "Location data is pseudonymised via coordinate rounding (~1 km² precision).",
  "Voice recordings are never permanently stored; deleted automatically at session end.",
  "Database access is restricted by role-based access control (RBAC).",
  "7. Cookies and Similar Technologies",
  "The App uses JWT-based authentication for session management. No third-party tracking cookies are used.",
  "8. Changes to This Notice",
  "When this Privacy Notice is updated, the new version will be published in the App and on our website. Users will be notified of material changes.",
  "9. Contact",
  "Veri Sorumlusu | Uptecra Teknoloji A.Ş.",
  "Adres | Zorlu Levent 199, Şişli, İstanbul, Türkiye",
  "E-posta | info@uptecra.com",
  "Yürürlük Tarihi | Mart 2026",
  "Veri | Amaç | Hukuki Dayanak | Süre",
  "Ad, Soyad | Hesap oluşturma ve kimlik doğrulama | Sözleşmenin ifası (KVKK m.5/2-c) | Hesap aktif olduğu sürece",
  "Telefon numarası | OTP ile kimlik doğrulama; SMS gönderimi | Sözleşmenin ifası (KVKK m.5/2-c) | Hesap aktif olduğu sürece",
  "Konum verisi (yuvarlanmış) | Rota planlama ve EV şarj optimizasyonu | Açık rıza (KVKK m.5/1 / GDPR m.6/1-a) | 12 ay",
  "Rota geçmişi | Geçmiş seyahatlerin görüntülenmesi | Açık rıza (KVKK m.5/1 / GDPR m.6/1-a) | 12 ay",
  "EV şarj bilgisi | Şarj durumuna göre rota optimizasyonu | Açık rıza (KVKK m.5/1 / GDPR m.6/1-a) | 12 ay",
  "Ses kaydı / transkript | EV şarj rota akışında sesli komut işleme | Açık rıza (KVKK m.5/1 / GDPR m.6/1-a) | Session sonu anında silinir",
  "Hız ve ivme verisi | Seyahat modunun tespiti (yürüyüş/araç vb.) | Meşru menfaat (KVKK m.5/2-f) | Cihaz içinde anlık; sunucuya gönderilmez",
  "Alıcı | Aktarım Amacı | Dayanak",
  "NetGSM (Türkiye) | OTP / SMS doğrulama | Sözleşmenin ifası; veri işleme sözleşmesi (DPA) mevcuttur",
  "Google LLC (ABD) | Geolocation API, Harita hizmeti | Açık rıza + AB Standart Sözleşme Maddeleri (SCCs); DPA mevcuttur",
  "ElevenLabs Inc. (ABD) | Sesli asistan işleme | Açık rıza + AB Standart Sözleşme Maddeleri (SCCs); DPA mevcuttur",
  "Apple Inc. (ABD) | Harita görselleştirme | Apple gizlilik politikası; kişisel veri aktarımı minimizedir",
  "Hak | Kapsam",
  "Bilgi edinme ve erişim | Verilerinizin işlenip işlenmediğini öğrenme; işleniyorsa bilgi talep etme",
  "Düzeltme | Yanlış veya eksik verilerin düzeltilmesini talep etme",
  "Silme (unutulma hakkı) | Hesabınızın ve tüm verilerinizin silinmesini talep etme",
  "İşlemeyi kısıtlama | Belirli işleme faaliyetlerinin durdurulmasını talep etme",
  "Veri taşınabilirliği | Verilerinizi makine okunabilir formatta (JSON) talep etme",
  "İtiraz | Meşru menfaate dayalı işleme faaliyetlerine itiraz etme",
  "Otomatik karara itiraz | Yalnızca otomatik işlemeye dayalı kararları itiraz etme (GDPR m.22)",
  "Şirket | Uptecra Teknoloji A.Ş.",
  "Adres | Zorlu Levent 199, Şişli, İstanbul, Türkiye",
  "E-posta | info@uptecra.com",
  "Data Controller | Uptecra Teknoloji A.S.",
  "Address | Zorlu Levent 199, Sisli, Istanbul, Turkey",
  "Email | info@uptecra.com",
  "Effective Date | March 2026",
  "Data | Purpose | Legal Basis | Retention",
  "Name, Surname | Account creation and identity verification | Performance of contract (KVKK Art.5/2-c) | Duration of account",
  "Phone number | OTP authentication; SMS delivery | Performance of contract (KVKK Art.5/2-c) | Duration of account",
  "Location (rounded) | Route planning and EV charge optimisation | Consent (KVKK Art.5/1 / GDPR Art.6/1-a) | 12 months",
  "Route history | Viewing past journeys | Consent (KVKK Art.5/1 / GDPR Art.6/1-a) | 12 months",
  "EV charge data | Route optimisation based on battery state | Consent (KVKK Art.5/1 / GDPR Art.6/1-a) | 12 months",
  "Voice recording / transcript | Processing voice commands in EV charge flow | Consent (KVKK Art.5/1 / GDPR Art.6/1-a) | Deleted immediately at session end",
  "Speed & acceleration | Travel mode detection (walking/driving etc.) | Legitimate interest (KVKK Art.5/2-f) | On-device only; never sent to servers",
  "Recipient | Transfer Purpose | Legal Basis",
  "NetGSM (Turkey) | OTP / SMS authentication | Performance of contract; DPA in place",
  "Google LLC (USA) | Geolocation API, Maps service | Consent + EU Standard Contractual Clauses (SCCs); DPA in place",
  "ElevenLabs Inc. (USA) | Voice assistant processing | Consent + EU Standard Contractual Clauses (SCCs); DPA in place",
  "Apple Inc. (USA) | Map visualisation | Apple Privacy Policy; personal data transfer is minimal",
  "Right | Scope",
  "Access and information | Learn whether your data is being processed and obtain a copy",
  "Rectification | Request correction of inaccurate or incomplete data",
  "Erasure (right to be forgotten) | Request deletion of your account and all personal data",
  "Restriction of processing | Request that certain processing activities be suspended",
  "Data portability | Receive your data in a machine-readable format (JSON)",
  "Objection | Object to processing based on legitimate interest",
  "Automated decision-making | Object to decisions based solely on automated processing (GDPR Art.22)",
  "Company | Uptecra Teknoloji A.S.",
  "Address | Zorlu Levent 199, Sisli, Istanbul, Turkey",
  "Email | info@uptecra.com"
] },
  terms: { title: "Kullanım Koşulları", paragraphs: [
  "KULLANIM KOŞULLARI",
  "Route Assistant Uygulaması",
  "1. Taraflar ve Kapsam",
  "Bu Kullanım Koşulları (\"Koşullar\"), Route Assistant uygulamasını (\"Uygulama\") kullanan kişi (\"Kullanıcı\") ile Uptecra Teknoloji A.Ş. (\"Şirket\") arasındaki hukuki ilişkiyi düzenlemektedir.",
  "Uygulamayı indirerek veya kullanarak bu Koşulları kabul etmiş sayılırsınız. Kabul etmiyorsanız Uygulamayı kullanmamanızı rica ederiz.",
  "2. Hizmet Kapsamı",
  "Route Assistant, elektrikli araç kullanıcılarına aşağıdaki hizmetleri sunmaktadır:",
  "Seyahat modu tespiti (yürüyüş, koşu, araç kullanımı)",
  "EV şarj ihtiyacına göre optimize edilmiş rota planlama",
  "Şarj istasyonu önerisi ve navigasyon entegrasyonu (Google Maps, Apple Maps)",
  "Sesli asistan aracılığıyla hands-free rota oluşturma",
  "Seyahat konforu için kişiselleştirilmiş tavsiyeler",
  "Şirket, hizmet kapsamını önceden bildirmeksizin genişletme veya daraltma hakkını saklı tutar.",
  "3. Kayıt ve Hesap",
  "Uygulamayı kullanmak için telefon numaranızla kayıt olmanız gerekmektedir.",
  "Kayıt sırasında sunulan Aydınlatma Metni ve bu Koşulları onaylamanız zorunludur.",
  "Hesabınızın güvenliğinden siz sorumlusunuz. Yetkisiz erişim durumunda info@uptecra.com adresine bildirmeniz gerekmektedir.",
  "18 yaşın altındaki bireyler Uygulamayı kullanamaz.",
  "4. Kullanıcı Yükümlülükleri",
  "Kullanıcı, Uygulamayı kullanırken aşağıdaki kurallara uymayı kabul eder:",
  "Uygulamayı yalnızca kişisel ve yasal amaçlarla kullanmak",
  "Üçüncü kişilerin kişisel verilerini rızaları olmaksızın sisteme girmemek",
  "Uygulamanın güvenlik mekanizmalarını aşmaya veya tersine mühendislik uygulamaya çalışmamak",
  "Araç kullanırken sesli komut dışındaki Uygulama özelliklerini kullanmamak (trafik güvenliği)",
  "Hatalı veya yanıltıcı bilgi girmemek",
  "5. Konum ve Ses Verisi Kullanımı",
  "Uygulama, rota planlama amacıyla konum verilerinize ve EV şarj akışı sırasında mikrofon erişimine ihtiyaç duymaktadır. Bu erişimler:",
  "Yalnızca açık rızanıza dayalı olarak gerçekleştirilir.",
  "Konum verisi ~1 km² hassasiyetinde saklanır; kesin adres kaydedilmez.",
  "Ses kayıtları oturum sonunda kalıcı olarak silinir.",
  "Hız ve ivme verisi yalnızca cihazınızda işlenir, sunucuya aktarılmaz.",
  "Konum veya mikrofon iznini dilediğiniz zaman cihaz ayarlarından kaldırabilirsiniz; bu durumda ilgili hizmetler çalışmayabilir.",
  "6. Fikri Mülkiyet",
  "Uygulama ve içeriğine ilişkin tüm fikri mülkiyet hakları Uptecra Teknoloji A.Ş.'ye aittir. Kullanıcıya yalnızca kişisel ve devredilemez bir kullanım lisansı tanınmaktadır.",
  "Uygulamayı kopyalamak, dağıtmak veya ticari amaçla kullanmak yasaktır.",
  "Uygulamanın kaynak koduna erişmeye çalışmak veya türev ürün oluşturmak yasaktır.",
  "7. Sorumluluk Sınırlaması",
  "Şirket, aşağıdaki durumlarda sorumluluk kabul etmez:",
  "Hatalı veya eksik rota bilgisinden kaynaklanan zararlar",
  "Üçüncü taraf harita ve navigasyon servislerinin (Google Maps, Apple Maps) hata veya kesintileri",
  "Kullanıcının trafik kurallarına veya güvenlik önlemlerine uymamasından kaynaklanan durumlar",
  "İnternet bağlantısı veya cihaz arızasından kaynaklanan hizmet kesintileri",
  "Mücbir sebep halleri (doğal afet, savaş, pandemi vb.)",
  "Uygulamanın sağladığı rota ve şarj önerileri bilgi amaçlıdır. Sürüş güvenliği her zaman kullanıcının sorumluluğundadır.",
  "8. Hizmet Kesintisi ve Değişiklikler",
  "Şirket, bakım, güncelleme veya teknik nedenlerle Uygulamayı geçici olarak askıya alabilir.",
  "Bu Koşullar önceden bildirim yapılarak değiştirilebilir. Önemli değişiklikler için Uygulama içi bildirim yapılacaktır.",
  "Değişiklik sonrası Uygulamayı kullanmaya devam etmeniz, yeni Koşulları kabul ettiğiniz anlamına gelir.",
  "9. Hesap Feshi",
  "Kullanıcı dilediği zaman Hesabım ekranından hesabını silebilir.",
  "Şirket, Koşulların ihlali halinde hesabı askıya alma veya silme hakkını saklı tutar.",
  "Hesap silindiğinde kişisel veriler 30 gün içinde kalıcı olarak imha edilir.",
  "10. Uygulanacak Hukuk ve Uyuşmazlık Çözümü",
  "Bu Koşullar, Türkiye Cumhuriyeti hukukuna tabidir. Doğabilecek uyuşmazlıklarda İstanbul Merkez Mahkemeleri ve İcra Daireleri yetkilidir.",
  "AB'de yerleşik kullanıcılar, tüketici hakları kapsamında yerel mahkemelere başvurma haklarını saklı tutar.",
  "11. İletişim",
  "TERMS OF SERVICE",
  "Route Assistant Application",
  "1. Parties and Scope",
  "These Terms of Service (\"Terms\") govern the legal relationship between the user of the Route Assistant application (\"User\") and Uptecra Teknoloji A.S. (\"Company\").",
  "By downloading or using the App, you agree to these Terms. If you do not agree, please do not use the App.",
  "2. Service Scope",
  "Route Assistant provides the following services to electric vehicle users:",
  "Travel mode detection (walking, running, driving)",
  "Optimised route planning based on EV charging needs",
  "Charging station recommendations and navigation integration (Google Maps, Apple Maps)",
  "Hands-free route creation via voice assistant",
  "Personalised recommendations for travel comfort",
  "The Company reserves the right to expand or limit the scope of services with prior notice.",
  "3. Registration and Account",
  "You must register with your phone number to use the App.",
  "You must accept the Privacy Notice and these Terms at registration.",
  "You are responsible for the security of your account. Report any unauthorised access to info@uptecra.com.",
  "Individuals under 18 years of age may not use the App.",
  "4. User Obligations",
  "By using the App, you agree to:",
  "Use the App only for personal and lawful purposes",
  "Not enter third parties' personal data without their consent",
  "Not attempt to bypass security mechanisms or reverse-engineer the App",
  "Not use App features other than voice commands while driving (road safety)",
  "Not provide false or misleading information",
  "5. Location and Voice Data Usage",
  "The App requires access to your location for route planning, and to your microphone during the EV charging flow. These accesses:",
  "Are carried out based solely on your explicit consent.",
  "Location data is stored at ~1 km² precision; exact addresses are never recorded.",
  "Voice recordings are permanently deleted at session end.",
  "Speed and acceleration data is processed on-device only and never transmitted to servers.",
  "You may revoke location or microphone permissions at any time in device settings; relevant features may then be unavailable.",
  "6. Intellectual Property",
  "All intellectual property rights relating to the App and its content are owned by Uptecra Teknoloji A.S. Users are granted a personal, non-transferable licence to use the App.",
  "Copying, distributing, or commercially using the App is prohibited.",
  "Attempting to access source code or creating derivative works is prohibited.",
  "7. Limitation of Liability",
  "The Company accepts no liability for:",
  "Damages arising from inaccurate or incomplete route information",
  "Errors or outages of third-party map and navigation services (Google Maps, Apple Maps)",
  "Consequences of the User's failure to comply with traffic rules or safety measures",
  "Service interruptions caused by internet connectivity or device failure",
  "Force majeure events (natural disaster, war, pandemic, etc.)",
  "Route and charging suggestions provided by the App are for informational purposes only. Driving safety is always the responsibility of the User.",
  "8. Service Interruptions and Changes",
  "The Company may temporarily suspend the App for maintenance, updates, or technical reasons.",
  "These Terms may be amended with prior notice. In-app notifications will be sent for material changes.",
  "Continued use of the App after changes constitutes acceptance of the new Terms.",
  "9. Account Termination",
  "Users may delete their account at any time via the Account section in the App.",
  "The Company reserves the right to suspend or delete accounts in case of breach of these Terms.",
  "Upon account deletion, personal data is permanently destroyed within 30 days.",
  "10. Governing Law and Dispute Resolution",
  "These Terms are governed by the laws of the Republic of Turkey. Istanbul Central Courts and Enforcement Offices have exclusive jurisdiction over any disputes.",
  "Users resident in the EU retain the right to bring proceedings before their local courts under applicable consumer protection laws.",
  "11. Contact",
  "Yayımlayan | Uptecra Teknoloji A.Ş.",
  "Yürürlük Tarihi | Mart 2026",
  "Uygulanacak Hukuk | Türkiye Cumhuriyeti Hukuku",
  "Şirket | Uptecra Teknoloji A.Ş.",
  "Adres | Zorlu Levent 199, Şişli, İstanbul, Türkiye",
  "E-posta | info@uptecra.com",
  "Publisher | Uptecra Teknoloji A.S.",
  "Effective Date | March 2026",
  "Governing Law | Republic of Turkey",
  "Company | Uptecra Teknoloji A.S.",
  "Address | Zorlu Levent 199, Sisli, Istanbul, Turkey",
  "Email | info@uptecra.com"
] },
};
